name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # chạy thủ công nếu cần

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (chromium only, folder tests) and write JSON
        # ghi output JSON vào results.json
        run: npx playwright test tests --project=chromium --reporter=json > results.json

      - name: Upload JSON report (optional, for debug)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-json
          path: results.json

      - name: Send results to n8n webhook
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          N8N_INCOMING_SECRET: ${{ secrets.N8N_INCOMING_SECRET }}
        run: |
          # gửi results.json thẳng tới webhook, kèm header bí mật để n8n xác thực
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "X-Run-Secret: $N8N_INCOMING_SECRET" \
            --data-binary @results.json \
            "$N8N_WEBHOOK_URL"
